### ISSUE TITLE
Birthday class

### ISSUE THREAD

**Issue by fustom** [allenporter/ical#299]
**Is your feature request related to a problem? Please describe.**
A component that stores birthdays.

**Describe the solution you'd like**
A derived class from ComponentModel. A constructor with birthday and a name parameters. Automatically set a yearly recurring, all day.  A calculated property that returns how old is she/he.

**Describe alternatives you've considered**
.

**Additional context**
.

**Comment by allenporter** [comment]
This is not part of rfc5525 and so I don't think this is in scope for this project. Respectfully, closing.
