### ISSUE TITLE
Wrong value in CalendarUserType enum

### ISSUE THREAD

**Issue by kunesj** [allenporter/ical#388]
The `RESOURCE` value of `CalendarUserType` [enum](https://github.com/allenporter/ical/blob/main/ical/types/cal_address.py#L30) is wrong.

It's:
```
RESOURCE = "GROUP"
```

But it should be:
```
RESOURCE = "RESOURCE"
```

**Comment by allenporter** [comment]
Thanks @kunesj 👍🏼
